#!/usr/bin/env python3
"""
Migration: Create web_early_access_codes table.

Invite codes for early-access registration gating.
Generated by admin (for Discord sharing) or the Fluxer bot !invite command.

Run from project root:
    python app/questlog_web/scripts/create_early_access_codes.py
"""

import sys
import os

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))

import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'casualsite.settings')
django.setup()

from sqlalchemy import text
from app.db import get_db_session

SQL = """
CREATE TABLE IF NOT EXISTS web_early_access_codes (
    id              INT AUTO_INCREMENT PRIMARY KEY,
    code            VARCHAR(16) NOT NULL,
    platform        VARCHAR(20) DEFAULT NULL,
    notes           VARCHAR(200) DEFAULT NULL,
    created_at      BIGINT NOT NULL,
    used_by_user_id INT DEFAULT NULL,
    used_at         BIGINT DEFAULT NULL,
    is_revoked      TINYINT(1) NOT NULL DEFAULT 0,
    UNIQUE KEY uq_eac_code (code),
    INDEX idx_eac_platform (platform),
    INDEX idx_eac_used (used_by_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
"""

with get_db_session() as db:
    db.execute(text(SQL))
    db.commit()
    print("OK: created web_early_access_codes table.")
